### ISSUE TITLE
Shared Library with Windows not showing files in VAN_DAM from Docker Desktop for Windows

### ISSUE THREAD

**Issue by jviehmeyer** [Floppy/van_dam#849]
I have files in the libraries/van_dam folder that I created - 3 STL files to be exact. However, they do not show in the web interface when I scan the library. 

Here is my compose file: 
```
version:` "3"

services:
  app:
    image: ghcr.io/floppy/van_dam:latest
    ports:
      - 3214:3214
    volumes:
      - C:\Users\jorda\Documents\van_dam:/libraries/van_dam
    environment:
      DATABASE_URL: postgresql://van_dam:password@172.20.0.3:5432/van_dam?pool=5
      SECRET_KEY_BASE: XXXXXXXXXX <-Redacted
      # RAILS_RELATIVE_URL_ROOT: /vandam Sets the root of the app to /vandam useful for reverse proxies with nginx
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: van_dam
      POSTGRES_PASSWORD: password
      POSTGRES_DB: van_dam
    restart: on-failure

  redis:
    image: redis:6
    restart: on-failure

volumes:
  db_data:
```

Here is what ls shows in the directory that it is mapped to: 
`drwxrwxrwx    1 root     root          4096 Dec  7 14:46 .
drwxr-xr-x    3 root     root          4096 Dec  7 14:53 ..
-rwxrwxrwx    1 root     root      25652784 Nov 28 01:17 5_Vertebrae_Loop.stl
-rwxrwxrwx    1 root     root      25018084 Nov 28 01:18 5_Vertebrae_Plain.stl
-rwxrwxrwx    1 root     root      77023984 Nov 23 21:48 Body1.stl`
